### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/harvest#1]
Found few misspellings.

"otherise" should be "otherwise"
"seeked" should be "sought"
"protocal" should be "protocol"

Please consider adding `typos` in a [workflow](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/spelling.yml).

**Comment by betterthanclay** [comment]
Thanks Viktor - I've fixed "otherise" and "protocal".. "seeked" was intentional to reflect the context of seeking (it is grammatically non-conformant throughout the interface).
